services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: key_creds
      KAFKA_SSL_TRUSTSTORE_CERTIFICATES: /etc/kafka/secrets/ca-cert.pem
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_creds

    volumes:
      - ./secrets:/etc/kafka/secrets

  auth_service:
    build: ./auth_service
    ports:
      - "8090:8090"
    volumes:
      - ./secrets:/app/secrets
    environment:
      - KAFKA_BROKER=localhost:9093
      - KAFKA_USERNAME=testuser
      - KAFKA_PASSWORD=testpassword

  track_service:
    build: ./track_service
    volumes:
      - ./secrets:/app/secrets
    environment:
      - KAFKA_BROKER=localhost:9093
      - KAFKA_USERNAME=testuser
      - KAFKA_PASSWORD=testpassword